version: '3'
services:
  postgres:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_USER: okemwag
      POSTGRES_PASSWORD: passwd123
      POSTGRES_DB: datacamp_db
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./data_pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"
